### ISSUE TITLE
Trying to install I get `ruby_source_dir_version': undefined method `[]'

### ISSUE THREAD

**Issue by jrgleason** [denofevil/debase#25]
I am trying to do...

`gem install debase` on Windows 10 I get

```
c:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/debase-ruby_core_source-0.8.1/lib/debase/ruby_core_source.rb:77:in `ruby_source_dir_version': undefined method `[]' for nil:NilClass (NoMethodError)
        from c:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/debase-ruby_core_source-0.8.1/lib/debase/ruby_core_source.rb:65:in `block in deduce_packaged_source_dir'
        from c:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/debase-ruby_core_source-0.8.1/lib/debase/ruby_core_source.rb:65:in `map'
        from c:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/debase-ruby_core_source-0.8.1/lib/debase/ruby_core_source.rb:65:in `deduce_packaged_source_dir'
        from c:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/debase-ruby_core_source-0.8.1/lib/debase/ruby_core_source.rb:43:in `create_makefile_with_core'
        from extconf.rb:47:in `<main>'
```

I don't see a command line arg or anything that I am missing. Anyone know what is wrong?

**Comment by os97673** [comment]
I'd suggest to update debase-ruby_code_source and if this will not help file bug against it os97673/debase-ruby_core_source
